/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package getsetjob;

import javax.swing.*;
import java.util.*;
import javax.swing.table.*;
import java.io.*;
import java.text.*;

public class Recruiter extends javax.swing.JFrame {

    ArrayList<Job> jobList = new ArrayList<>();
    DefaultTableModel dtm;

    public Recruiter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        titlePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jobPostField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        skillComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        fullTimeRadioButton = new javax.swing.JRadioButton();
        partTimeRadioButton = new javax.swing.JRadioButton();
        internRadioButton = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        vacancyField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        postButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        tablePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(200, 110));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        titlePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HiziBizi group of Companies");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        formPanel.setBackground(new java.awt.Color(153, 153, 153));
        formPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        formPanel.setLayout(new java.awt.GridLayout(9, 0, 4, 4));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name of the Post");
        formPanel.add(jLabel2);
        formPanel.add(jobPostField);

        jLabel3.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Type");
        formPanel.add(jLabel3);

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Software Enginer", "Web Developer", "Marketing manager", "App Developer", "DevOps Enginer" }));
        formPanel.add(typeComboBox);

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Field of expertice");
        formPanel.add(jLabel5);

        skillComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Java", "C++", "Python", "Ruby", "Kotlin" }));
        formPanel.add(skillComboBox);

        jLabel8.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Employee type");
        formPanel.add(jLabel8);

        buttonGroup1.add(fullTimeRadioButton);
        fullTimeRadioButton.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        fullTimeRadioButton.setText("Full time");
        fullTimeRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fullTimeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullTimeRadioButtonActionPerformed(evt);
            }
        });
        formPanel.add(fullTimeRadioButton);

        buttonGroup1.add(partTimeRadioButton);
        partTimeRadioButton.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        partTimeRadioButton.setText("Par time");
        partTimeRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formPanel.add(partTimeRadioButton);

        buttonGroup1.add(internRadioButton);
        internRadioButton.setFont(new java.awt.Font("Sitka Banner", 1, 14)); // NOI18N
        internRadioButton.setText("Intern");
        internRadioButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        formPanel.add(internRadioButton);

        jLabel10.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Vacancy");
        formPanel.add(jLabel10);
        formPanel.add(vacancyField);

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Deadline");
        formPanel.add(jLabel9);
        formPanel.add(dateChooser);

        postButton.setText("Post Job");
        postButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postButtonActionPerformed(evt);
            }
        });
        formPanel.add(postButton);

        deleteButton.setText("Delete Post");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        formPanel.add(deleteButton);

        updateButton.setText("Update Post");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        formPanel.add(updateButton);

        exitButton.setText("Exit Portal");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        formPanel.add(exitButton);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Post", "Type", "Skill", "Job type", "Deadline", "Vacancy"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout tablePanelLayout = new javax.swing.GroupLayout(tablePanel);
        tablePanel.setLayout(tablePanelLayout);
        tablePanelLayout.setHorizontalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );
        tablePanelLayout.setVerticalGroup(
            tablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fullTimeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullTimeRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullTimeRadioButtonActionPerformed

    private void postButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postButtonActionPerformed
        String p0st, typ3, sk1ll, empTyp3 = "", vacancy, d3adline;

        p0st = jobPostField.getText();
        typ3 = typeComboBox.getSelectedItem().toString();
        sk1ll = skillComboBox.getSelectedItem().toString();

        if (fullTimeRadioButton.isSelected()) {
            empTyp3 = "Full Time";
        }
        if (partTimeRadioButton.isSelected()) {
            empTyp3 = "Part Time";
        }
        if (internRadioButton.isSelected()) {
            empTyp3 = "Intern";
        }
        vacancy = vacancyField.getText();
        d3adline = ((JTextField) dateChooser.getDateEditor().getUiComponent()).getText();

        if (p0st.equals("")) {
            JOptionPane.showMessageDialog(null, "Enter post Title", "Insertion error", 0);
        } else if (typeComboBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Select job type", "Insertion error", 0);
        } else if (skillComboBox.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Select skills", "Insertion error", 0);
        } else if (empTyp3.equals("")) {
            JOptionPane.showMessageDialog(null, "Enter employee type", "Insertion error", 0);
        } else if (vacancy.equals("")) {
            JOptionPane.showMessageDialog(null, "Enter vacancy", "Insertion error", 0);
        } else if (d3adline.equals("")) {
            JOptionPane.showMessageDialog(null, "Enter deadline", "Insertion error", 0);
        } else {
            Job j = new Job(p0st, typ3, sk1ll, empTyp3, d3adline, Integer.parseInt(vacancy));
            jobList.add(j);

            dtm = (DefaultTableModel) jTable1.getModel();
            dtm.setRowCount(0);
            Object row[] = new Object[8];
            for (Job x : jobList) {
                row[0] = x.post;
                row[1] = x.type;
                row[2] = x.skill;
                row[3] = x.empType;
                row[4] = x.deadline;
                row[5] = x.vacancy;
                dtm.addRow(row);
            }
            jobPostField.setText("");
            typeComboBox.setSelectedIndex(0);
            skillComboBox.setSelectedIndex(0);
            buttonGroup1.clearSelection();
            vacancyField.setText("");
            dateChooser.setCalendar(null);
        }
    }//GEN-LAST:event_postButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        int p = JOptionPane.showConfirmDialog(this, "Are you want to exit?", "Confirmation", 0, 2);
        if (p == 0) {
            try {
                FileWriter fw = new FileWriter("jobList.txt", true);
                BufferedWriter bw = new BufferedWriter(fw);

                for (Job x : jobList) {
                    bw.write(x.post + " " + x.type + " " + x.skill + " " + x.empType + " " + x.deadline + " " + x.vacancy);
                    bw.newLine();
                }
                bw.close();
            } catch (IOException ex) {
            }
            System.exit(0);
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        dtm = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRowCount() == 1) {
            int index = jTable1.getSelectedRow();
            int p = JOptionPane.showConfirmDialog(this, "Are you want to DELETE this post?", "Confirm deletion", 0, 2);
            if (p == 0) {
                dtm.removeRow(index);
                jobList.remove(index);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Select only one job", "Multiple jobs selected", 2);
        }
        jobPostField.setText("");
        typeComboBox.setSelectedIndex(0);
        skillComboBox.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        vacancyField.setText("");
        dateChooser.setCalendar(null);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int p = JOptionPane.showConfirmDialog(this, "Are you want to exit?", "Confirmation", 0, 2);
        if (p == 0) {
            try {
                FileWriter fw = new FileWriter("jobList.txt", true);
                BufferedWriter bw = new BufferedWriter(fw);

                for (Job x : jobList) {
                    bw.write(x.post + " " + x.type + " " + x.skill + " " + x.empType + " " + x.deadline + " " + x.vacancy);
                    bw.newLine();
                }
                bw.close();
            } catch (IOException ex) {
            }
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            int index = jTable1.getSelectedRow();
            String p0st, typ3, sk1ll, empTyp3 = "", vacancy, d3adline;
            p0st = jTable1.getValueAt(index, 0).toString();
            typ3 = jTable1.getValueAt(index, 1).toString();
            sk1ll = jTable1.getValueAt(index, 2).toString();
            empTyp3 = jTable1.getValueAt(index, 3).toString();
            d3adline = jTable1.getValueAt(index, 4).toString();
            vacancy = jTable1.getValueAt(index, 5).toString(); // Corrected index for the vacancy field
            jobPostField.setText(p0st);
            typeComboBox.setSelectedItem(typ3);
            skillComboBox.setSelectedItem(sk1ll);

            // Clearing selection before setting the radio buttons
            buttonGroup1.clearSelection();

            if (empTyp3.equals("Full Time")) {
                fullTimeRadioButton.setSelected(true);
            } else if (empTyp3.equals("Part Time")) {
                partTimeRadioButton.setSelected(true);
            } else if (empTyp3.equals("Intern")) {
                internRadioButton.setSelected(true);
            }

            vacancyField.setText(vacancy);
            Date d = new SimpleDateFormat("MMM d, y").parse((String) d3adline);
            dateChooser.setDate(d);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        String p0st, typ3, sk1ll, empTyp3 = "", vacancy, d3adline;

        p0st = jobPostField.getText();
        typ3 = typeComboBox.getSelectedItem().toString();
        sk1ll = skillComboBox.getSelectedItem().toString();

        if (fullTimeRadioButton.isSelected()) {
            empTyp3 = "Full Time";
        }
        if (partTimeRadioButton.isSelected()) {
            empTyp3 = "Part Time";
        }
        if (internRadioButton.isSelected()) {
            empTyp3 = "Intern";
        }
        vacancy = vacancyField.getText();
        d3adline = ((JTextField) dateChooser.getDateEditor().getUiComponent()).getText();

        Job j = new Job(p0st, typ3, sk1ll, empTyp3, d3adline, Integer.parseInt(vacancy));
        jobList.add(j);

        dtm = (DefaultTableModel) jTable1.getModel();
        int index = jTable1.getSelectedRow();
        dtm.removeRow(index);
        jobList.remove(index);
        dtm.setRowCount(0);
        Object row[] = new Object[8];
        for (Job x : jobList) {
            row[0] = x.post;
            row[1] = x.type;
            row[2] = x.skill;
            row[3] = x.empType;
            row[4] = x.deadline;
            row[5] = x.vacancy;
            dtm.addRow(row);
        }

        jobPostField.setText("");
        typeComboBox.setSelectedIndex(0);
        skillComboBox.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        vacancyField.setText("");
        dateChooser.setCalendar(null);
    }//GEN-LAST:event_updateButtonActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recruiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recruiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recruiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recruiter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recruiter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel formPanel;
    private javax.swing.JRadioButton fullTimeRadioButton;
    private javax.swing.JRadioButton internRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jobPostField;
    private javax.swing.JRadioButton partTimeRadioButton;
    private javax.swing.JButton postButton;
    private javax.swing.JComboBox<String> skillComboBox;
    private javax.swing.JPanel tablePanel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JButton updateButton;
    private javax.swing.JTextField vacancyField;
    // End of variables declaration//GEN-END:variables
}
