package getsetjob;

import java.io.*;
import java.util.*;
import javax.swing.table.*;
import javax.swing.*;

public class Seeker extends javax.swing.JFrame {

    ArrayList<Applicant> applicantList = new ArrayList<>();
    DefaultTableModel dtm;
    Object row[] = new Object[7];

    public Seeker() {
        initComponents();
        try {
            FileReader fr = new FileReader("jobList.txt");
            BufferedReader br = new BufferedReader(fr);
            String line;

            while ((line = br.readLine()) != null) {
                String lineArr[] = line.split(" ");
                dtm = (DefaultTableModel) jTable1.getModel();
                row[0] = lineArr[0];
                row[1] = lineArr[1] + " " + lineArr[2];
                row[2] = lineArr[3];
                row[3] = lineArr[4];
                row[4] = lineArr[5] + " " + lineArr[6] + " " + lineArr[7];
                row[5] = lineArr[8];
                dtm.addRow(row);
            }
        } catch (Exception e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        eduComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ageField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        postField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        typeField = new javax.swing.JTextField();
        applyButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Post", "Type", "Skill", "Job Type", "Deadline", "Vacancy"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.setLayout(new java.awt.GridLayout(6, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Name");
        jPanel2.add(jLabel1);
        jPanel2.add(nameField);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Level of Education");
        jPanel2.add(jLabel2);

        eduComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "BSc.", "Diploma", "Self Educated" }));
        jPanel2.add(eduComboBox);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Age");
        jPanel2.add(jLabel4);
        jPanel2.add(ageField);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Post");
        jPanel2.add(jLabel3);

        postField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postFieldActionPerformed(evt);
            }
        });
        jPanel2.add(postField);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Type");
        jPanel2.add(jLabel5);

        typeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeFieldActionPerformed(evt);
            }
        });
        jPanel2.add(typeField);

        applyButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        applyButton.setText("Appy");
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });
        jPanel2.add(applyButton);

        exitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel2.add(exitButton);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void postFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postFieldActionPerformed

    }//GEN-LAST:event_postFieldActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        int p = JOptionPane.showConfirmDialog(this, "Are you want to exit?", "Confirmation", 0, 2);
        if (p == 0) {
            try {
                FileWriter fw = new FileWriter("applicantList.txt", true);
                BufferedWriter bw = new BufferedWriter(fw);

                for (Applicant x : applicantList) {
                    bw.write(x.name + " " + x.edu + " " + x.age + " " + x.post + " " + x.type);
                    bw.newLine();
                }
                bw.close();
            } catch (IOException ex) {
            }
            System.exit(0);
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        try {
            int i = jTable1.getSelectedRow();
            String a = dtm.getValueAt(i, 0).toString();
            String b = dtm.getValueAt(i, 1).toString();
            postField.setText(a);
            typeField.setText(b);
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void typeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeFieldActionPerformed

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
        try {
            FileWriter fw = new FileWriter("applicantList.txt", true);
            BufferedWriter bw = new BufferedWriter(fw);

            String name, edu, age, post, type;
            name = nameField.getText();
            edu = eduComboBox.getSelectedItem().toString();
            age = ageField.getText();
            post = postField.getText();
            type = typeField.getText();

            if (name.equals("")) {
                JOptionPane.showMessageDialog(null, "Enter name", "Insertion error", 0);
            } else if (edu.equals("")) {
                JOptionPane.showMessageDialog(null, "Enter name", "Insertion error", 0);
            } else if (age.equals("")) {
                JOptionPane.showMessageDialog(null, "Enter name", "Insertion error", 0);
            } else if (post.equals("")) {
                JOptionPane.showMessageDialog(null, "Enter name", "Insertion error", 0);
            } else if (type.equals("")) {
                JOptionPane.showMessageDialog(null, "Enter name", "Insertion error", 0);
            } else {
                Applicant a = new Applicant(name, edu, age, post, type);
                applicantList.add(a);
                nameField.setText("");
                eduComboBox.setSelectedIndex(0);
                ageField.setText("");
                postField.setText("");
                typeField.setText("");
                bw.close();
            }
        } catch (Exception e) {

        }

    }//GEN-LAST:event_applyButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int p = JOptionPane.showConfirmDialog(this, "Are you want to exit?", "Confirmation", 0, 2);
        if (p == 0) {
            try {
                FileWriter fw = new FileWriter("applicantList.txt", true);
                BufferedWriter bw = new BufferedWriter(fw);

                for (Applicant x : applicantList) {
                    bw.write(x.name + " " + x.edu + " " + x.age + " " + x.post + " " + x.type);
                    bw.newLine();
                }
                bw.close();
            } catch (IOException ex) {
            }
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seeker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seeker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seeker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seeker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seeker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageField;
    private javax.swing.JButton applyButton;
    private javax.swing.JComboBox<String> eduComboBox;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField postField;
    private javax.swing.JTextField typeField;
    // End of variables declaration//GEN-END:variables
}
